modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://www.github.com/nertzhuldev/creepy-creepers/issues"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/creepy-creepers"
    logoFile = "icon.png"
    credits = "KiriCattus, Paint_Ninja"
    authors = "${mod_authors}"
    description = '''${mod_description}'''

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    mandatory = true
    versionRange = "${neoforge_version_range}"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"